### PR TITLE
Refactor 2

### PR DESCRIPTION
**Pull request by popojan**
Refactor seems viable.
* some bug fixes thanks to @lj739's feedback
* undoing moves works again
* komi and engine selection using drop down menus
* komi independent of handicap, possible values listed in `data/gui/goban.rml`
* fixed secondary engine confusion when switching it during game
* end of game by resignation handled correctly

### CODE REVIEW

**Comment by lj739** [comment]
Please renew the binary file.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jan Popelka"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月16日(星期六) 晚上8:10
收件人:&nbsp;"popojan/goban"<goban@noreply.github.com&gt;;
抄送:&nbsp;"费而隐"<909417887@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;[popojan/goban] Refactor 2 (#20)




Refactor seems viable.
  
some bug fixes thanks to @lj739's feedback
 
undoing moves works again
 
komi and engine selection using drop down menus
 
komi independent of handicap, possible values listed in data/gui/goban.rml
 
fixed secondary engine confusion when switching it during game
 
end of game by resignation handled correctly
  
 
You can view, comment on, or merge this pull request online at:
 
&nbsp; https://github.com/popojan/goban/pull/20
 
Commit Summary
    
configurable komi wip
   
refactor-2 leftovers
   
#17 drop down komi selection WIP
   
#17 change engines using drop down list
   
#17 fix drop down layout
   
reenable move sound, fix stuck territory markers
   
strange behaviour on small screens
   
#18 take back move fixed
   
#15 quick ugly fix
   
#19 all engines follow the game even when inactive
   
clean some code commented out
   
#16 show influence after resignation
  
File Changes
    
     M     CMakeLists.txt     (3)   
   
     M     data/gui/goban.rcss     (85)   
   
     M     data/gui/goban.rml     (42)   
   
     M     src/Board.cpp     (16)   
   
     M     src/Board.h     (10)   
   
     M     src/BoardObserver.h     (1)   
   
     M     src/ElementGame.cpp     (93)   
   
     M     src/ElementGame.h     (1)   
   
     M     src/EventHandlerNewGame.cpp     (36)   
   
     M     src/EventHandlerNewGame.h     (4)   
   
     M     src/GameObserver.h     (5)   
   
     M     src/GameState.h     (11)   
   
     M     src/GameThread.cpp     (184)   
   
     M     src/GameThread.h     (28)   
   
     M     src/GobanControl.cpp     (52)   
   
     M     src/GobanControl.h     (5)   
   
     M     src/GobanModel.cpp     (68)   
   
     M     src/GobanModel.h     (25)   
   
     M     src/GobanView.cpp     (45)   
   
     M     src/GobanView.h     (4)   
   
     M     src/opengl.h     (2)   
   
     M     src/player.cpp     (4)   
   
     M     src/player.h     (4)   
   
     M     src/shell/include/ShellOpenGL.h     (2)   
  
Patch Links:
    
https://github.com/popojan/goban/pull/20.patch
   
https://github.com/popojan/goban/pull/20.diff

**Comment by popojan** [comment]
Here: [hraj.si/goban/goban_2020-05-16_refactor-2.zip](https://hraj.si/goban/goban_2020-05-16_refactor-2.zip).
Only `goban.exe` has changed, though.
Thank you for testing!

**Comment by popojan** [comment]
@lj739 Please tell me if you run into any bugs, in yesterday's build.

**Comment by lj739** [comment]
I'd given goban to some friends to test, they all acknowledged it is a great interface of go and would have wonderful future. I also let my 7 years old child use it, he like it very much. Since katago support any size of board now, I suppose 15X15 and 17x17 would be welcome. Now goban have had the most important functions already, but there are still many aspects need to be improved. On my view, the first is gtp console, the second, open and save sgf files(including of browse backward and forward in current sgf opened), the third, analyzing. &nbsp;&nbsp;
I have tested the new version for two days, territory still not working, but I can precisely get this information from katago's gtp output log. &nbsp;

**Comment by popojan** [comment]
Thank you for your kind words. I'll do my best to come up with some features sooner than in a year ;) Yesterday I compiled katago from sources on my linux dev machine. It works fine even with the integrated Intel HD graphics, so there is no blocker to incorporate some of the great features of katago into goban (except days having only 24 hours, indeed). I may want to ask you for details and discuss the proposed features, so please be around if you can. Have a nice time!

By territory not working you mean showing incorrect ownership or completely broken?

**Comment by lj739** [comment]
Territory&nbsp; completely broken, can not&nbsp;show at the end of game, but it doesn't matter. For go players, computing territory is a basic skill,&nbsp; I suppose&nbsp; they will not regart it as a&nbsp; indispensable function, and all they need are katago's gtp&nbsp;console&nbsp;information about winrate and leading stones. Other go interface like sabaki, lizgoban can show&nbsp; territory at the end of game, but in the middle of game, showing territory is not a reliable thing,&nbsp; only katago's info can be&nbsp;&nbsp;
relyed on. It is a pleasure to help improving gaban, if you have any question, do not hesitate to contack me.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jan Popelka"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月18日(星期一) 晚上7:44
收件人:&nbsp;"popojan/goban"<goban@noreply.github.com&gt;;
抄送:&nbsp;"费而隐"<909417887@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [popojan/goban] Refactor 2 (#20)





 
Thank you for your kind words. I'll do my best to come up with some features sooner than in a year ;) Yesterday I compiled katago from sources on my linux dev machine. It works fine even with the integrated Intel HD graphics, so there is no blocker to incorporate some of the great features of katago into goban (except days having only 24 hours, indeed). I may want to ask you for details and discuss the proposed features, so please be around if you can. Have a nice time!
 
By territory not working you mean showing incorrect ownership or completely broken?

**Comment by popojan** [comment]
Thanks for a quick reply, very strange, if you do not touch Territory button, it should show up automatically at the end of the game and disappear when you start a new game. Anytime, you can toggle territory using the button. Midgame you have to wait for a bot move to complete. When game ends by resignation, what goban display is only the dubious mid-game ownership. Let's debug it when you have time, you could submit a new issue, please.

**Comment by lj739** [comment]
I've&nbsp; found the reason,&nbsp; katago engine(1.42 cuda) had caused territory failing to show. On the initial time(no other engines enabled except official engine), territory shown properly. I've got no time to test more engines. Usually I would delete pachi engine, because goban will report a error at launch time if the number of engines exceeds five.

**Comment by popojan** [comment]
Thanks for narrowing down the problem. I will check it later on my windows box with nvidia card. Now I am reworking and decluttering GUI to make room for GTP console and other new elements.

**Comment by popojan** [comment]
Already merged as part of gui refactor.

**Pull request closed without merging**
